# backend/app/models/enums.py
import enum


class ProjectState(str, enum.Enum):
    DRAFT = "DRAFT"
    REQS_REFINING = "REQS_REFINING"
    REQS_READY = "REQS_READY"
    CODE_VALIDATED = "CODE_VALIDATED"
    PLAN_READY = "PLAN_READY"
    PROMPTS_READY = "PROMPTS_READY"
    DONE = "DONE"
    BLOCKED = "BLOCKED"


class AgentType(str, enum.Enum):
    REQUIREMENTS = "REQUIREMENTS"
    REFINE = "REFINE"
    PLAN = "PLAN"
    PROMPTS = "PROMPTS"
    VALIDATION = "VALIDATION"


class EventType(str, enum.Enum):
    STATE_TRANSITION = "STATE_TRANSITION"
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"
    ERROR_OCCURRED = "ERROR_OCCURRED"
    USER_ACTION = "USER_ACTION"
    VALIDATION_PASSED = "VALIDATION_PASSED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    SYSTEM_EVENT = "SYSTEM_EVENT"
    RETRY_ATTEMPTED = "RETRY_ATTEMPTED"
